from typing import Dict, List
import os

try:
    from google import generativeai as genai
except ImportError:
    genai = None


class GoogleLLMClient:
    """Thin wrapper around Google AI SDK. Falls back to a stub if SDK/key is missing."""

    def __init__(self, api_key: str, model_name: str = "gemini-1.5-pro"):
        self.api_key = api_key or os.getenv("GOOGLE_API_KEY", "")
        self.model_name = model_name
        self._client = None
        if genai and self.api_key:
            genai.configure(api_key=self.api_key)
            self._client = genai.GenerativeModel(self.model_name)

    def chat(self, system_prompt: str, user_content: str) -> str:
        # Fallback stub to keep repo runnable without secrets
        if not self._client:
            return (
                "Stub SariCoach response based on analysis JSON. "
                "In the real environment, this is generated by Gemini."
            )

        prompt = f"{system_prompt}\n\nUser:\n{user_content}"
        resp = self._client.generate_content(prompt)
        return resp.text or ""
